activation: gelu
alias: null
attn_dropout: 0.0
batch_normalization: false
batch_size: 32
dataloader_kwargs: null
drop_last_loader: false
dropout: 0.2
early_stop_patience_steps: -1
encoder_layers: 3
exclude_insample_y: false
fc_dropout: 0.2
futr_exog_list: null
h: 24
h_train: 1
head_dropout: 0.0
hidden_size: 128
hist_exog_list: null
inference_input_size: 199
inference_windows_batch_size: 1024
input_size: 199
learn_pos_embed: true
learning_rate: 0.0001
linear_hidden_size: 256
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 200
n_heads: 16
n_samples: 100
n_series: 1
num_lr_decays: -1
optimizer: null
optimizer_kwargs: null
patch_len: 16
random_seed: 1
res_attention: true
revin: true
revin_affine: false
revin_subtract_last: true
scaler_type: identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
stride: 8
training_data_availability_threshold: 0.0
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
